/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksWorkersRouteImport } from './routes/tasks.workers'
import { Route as TasksJobIdRouteImport } from './routes/tasks.$jobId'
import { Route as EditorLocalRouteImport } from './routes/editor.local'
import { Route as EditorFileIdRouteImport } from './routes/editor.$fileId'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksWorkersRoute = TasksWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => TasksRoute,
} as any)
const TasksJobIdRoute = TasksJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => TasksRoute,
} as any)
const EditorLocalRoute = EditorLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => EditorRoute,
} as any)
const EditorFileIdRoute = EditorFileIdRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => EditorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cloud': typeof CloudRoute
  '/editor': typeof EditorRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/editor/$fileId': typeof EditorFileIdRoute
  '/editor/local': typeof EditorLocalRoute
  '/tasks/$jobId': typeof TasksJobIdRoute
  '/tasks/workers': typeof TasksWorkersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cloud': typeof CloudRoute
  '/editor': typeof EditorRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/editor/$fileId': typeof EditorFileIdRoute
  '/editor/local': typeof EditorLocalRoute
  '/tasks/$jobId': typeof TasksJobIdRoute
  '/tasks/workers': typeof TasksWorkersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cloud': typeof CloudRoute
  '/editor': typeof EditorRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/editor/$fileId': typeof EditorFileIdRoute
  '/editor/local': typeof EditorLocalRoute
  '/tasks/$jobId': typeof TasksJobIdRoute
  '/tasks/workers': typeof TasksWorkersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cloud'
    | '/editor'
    | '/tasks'
    | '/editor/$fileId'
    | '/editor/local'
    | '/tasks/$jobId'
    | '/tasks/workers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cloud'
    | '/editor'
    | '/tasks'
    | '/editor/$fileId'
    | '/editor/local'
    | '/tasks/$jobId'
    | '/tasks/workers'
  id:
    | '__root__'
    | '/'
    | '/cloud'
    | '/editor'
    | '/tasks'
    | '/editor/$fileId'
    | '/editor/local'
    | '/tasks/$jobId'
    | '/tasks/workers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CloudRoute: typeof CloudRoute
  EditorRoute: typeof EditorRouteWithChildren
  TasksRoute: typeof TasksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/workers': {
      id: '/tasks/workers'
      path: '/workers'
      fullPath: '/tasks/workers'
      preLoaderRoute: typeof TasksWorkersRouteImport
      parentRoute: typeof TasksRoute
    }
    '/tasks/$jobId': {
      id: '/tasks/$jobId'
      path: '/$jobId'
      fullPath: '/tasks/$jobId'
      preLoaderRoute: typeof TasksJobIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/editor/local': {
      id: '/editor/local'
      path: '/local'
      fullPath: '/editor/local'
      preLoaderRoute: typeof EditorLocalRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/$fileId': {
      id: '/editor/$fileId'
      path: '/$fileId'
      fullPath: '/editor/$fileId'
      preLoaderRoute: typeof EditorFileIdRouteImport
      parentRoute: typeof EditorRoute
    }
  }
}

interface EditorRouteChildren {
  EditorFileIdRoute: typeof EditorFileIdRoute
  EditorLocalRoute: typeof EditorLocalRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorFileIdRoute: EditorFileIdRoute,
  EditorLocalRoute: EditorLocalRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

interface TasksRouteChildren {
  TasksJobIdRoute: typeof TasksJobIdRoute
  TasksWorkersRoute: typeof TasksWorkersRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksJobIdRoute: TasksJobIdRoute,
  TasksWorkersRoute: TasksWorkersRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CloudRoute: CloudRoute,
  EditorRoute: EditorRouteWithChildren,
  TasksRoute: TasksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
