/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorLocalRouteImport } from './routes/editor.local'
import { Route as EditorFileIdRouteImport } from './routes/editor.$fileId'

const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorLocalRoute = EditorLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => EditorRoute,
} as any)
const EditorFileIdRoute = EditorFileIdRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => EditorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cloud': typeof CloudRoute
  '/editor': typeof EditorRouteWithChildren
  '/editor/$fileId': typeof EditorFileIdRoute
  '/editor/local': typeof EditorLocalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cloud': typeof CloudRoute
  '/editor': typeof EditorRouteWithChildren
  '/editor/$fileId': typeof EditorFileIdRoute
  '/editor/local': typeof EditorLocalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cloud': typeof CloudRoute
  '/editor': typeof EditorRouteWithChildren
  '/editor/$fileId': typeof EditorFileIdRoute
  '/editor/local': typeof EditorLocalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cloud' | '/editor' | '/editor/$fileId' | '/editor/local'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cloud' | '/editor' | '/editor/$fileId' | '/editor/local'
  id:
    | '__root__'
    | '/'
    | '/cloud'
    | '/editor'
    | '/editor/$fileId'
    | '/editor/local'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CloudRoute: typeof CloudRoute
  EditorRoute: typeof EditorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/local': {
      id: '/editor/local'
      path: '/local'
      fullPath: '/editor/local'
      preLoaderRoute: typeof EditorLocalRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/$fileId': {
      id: '/editor/$fileId'
      path: '/$fileId'
      fullPath: '/editor/$fileId'
      preLoaderRoute: typeof EditorFileIdRouteImport
      parentRoute: typeof EditorRoute
    }
  }
}

interface EditorRouteChildren {
  EditorFileIdRoute: typeof EditorFileIdRoute
  EditorLocalRoute: typeof EditorLocalRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorFileIdRoute: EditorFileIdRoute,
  EditorLocalRoute: EditorLocalRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CloudRoute: CloudRoute,
  EditorRoute: EditorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
