//! Code generation — Rust ports of `packages/pen-codegen/src/`.
//! v1 ships the simplest of the 9 TS generators: `css-variables`,
//! which emits the design's `Document.var_table` as CSS custom
//! properties. Future generators (React + Tailwind, HTML, Vue,
//! Svelte, Flutter, SwiftUI, Compose, React Native) live behind
//! the same `Codegen` trait so a single dispatcher (eventually a
//! `op codegen <target>` CLI) can fan out by target enum.

use crate::document::{Document, Node, NodeKind, VariableScalar, VariableValue};
use crate::Color;

/// One generator. Implementations are pure (read `Document`, return
/// `String`); the CLI / panel layer owns file-write side effects.
pub trait Codegen {
    fn target_label(&self) -> &'static str;
    fn generate(&self, doc: &Document) -> String;
}

/// CSS custom properties generator. Walks `doc.var_table` and emits
/// `:root { --name: value; }`. Color variables stay as their hex
/// string; number/bool/string variables stringify their scalar.
/// Themed values emit ONE entry per theme combination using a
/// `:root[data-axis="value"]` selector so the same CSS reflows
/// across theme switches with no JS.
pub struct CssVariables;

impl Codegen for CssVariables {
    fn target_label(&self) -> &'static str {
        "css-variables"
    }
    fn generate(&self, doc: &Document) -> String {
        let mut out = String::new();
        out.push_str("/* Generated by OpenPencil — codegen::CssVariables */\n");
        // Pass 1: scalar (theme-agnostic) variables go under :root.
        let mut root_scalars: Vec<(String, String)> = Vec::new();
        for v in &doc.var_table.variables {
            if let VariableValue::Scalar(s) = &v.value {
                root_scalars.push((v.name.clone(), scalar_to_css(s)));
            }
        }
        if !root_scalars.is_empty() {
            out.push_str(":root {\n");
            for (name, value) in &root_scalars {
                out.push_str(&format!("  --{}: {};\n", css_ident(name), value));
            }
            out.push_str("}\n");
        }
        // Pass 2: themed variables → one block per (axis, value) combo.
        // Group entries by their theme map signature so a "mode=dark"
        // entry from variable A and another from B share one block.
        use std::collections::BTreeMap;
        let mut themed: BTreeMap<Vec<(String, String)>, Vec<(String, String)>> = BTreeMap::new();
        for v in &doc.var_table.variables {
            if let VariableValue::Themed(entries) = &v.value {
                for e in entries {
                    let key: Vec<(String, String)> = e
                        .theme
                        .as_ref()
                        .map(|m| m.iter().map(|(k, v)| (k.clone(), v.clone())).collect())
                        .unwrap_or_default();
                    themed
                        .entry(key)
                        .or_default()
                        .push((v.name.clone(), scalar_to_css(&e.value)));
                }
            }
        }
        for (axes, decls) in &themed {
            if axes.is_empty() {
                out.push_str(":root {\n");
            } else {
                let sel = axes
                    .iter()
                    .map(|(k, v)| format!("[data-{}=\"{}\"]", k, v))
                    .collect::<Vec<_>>()
                    .join("");
                out.push_str(&format!(":root{} {{\n", sel));
            }
            for (name, value) in decls {
                out.push_str(&format!("  --{}: {};\n", css_ident(name), value));
            }
            out.push_str("}\n");
        }
        out
    }
}

/// HTML + inline-CSS generator. Walks the active page's node tree
/// and emits `<div>` per Rect/Frame/Group with absolute positioning
/// and inline style; ellipses get `border-radius: 50%`; text nodes
/// emit `<span>`. Bare minimum useful — refining to semantic tags
/// + flex containers is a follow-up.
pub struct Html;

impl Codegen for Html {
    fn target_label(&self) -> &'static str {
        "html"
    }
    fn generate(&self, doc: &Document) -> String {
        let mut out = String::new();
        out.push_str("<!-- Generated by OpenPencil — codegen::Html -->\n");
        out.push_str("<!DOCTYPE html>\n<html><head><meta charset=\"utf-8\"></head>\n<body>\n");
        if let Some(page) = doc.pages.get(doc.active_page_index) {
            for node in &page.children {
                emit_node_html(&mut out, node, 1);
            }
        }
        out.push_str("</body></html>\n");
        out
    }
}

fn emit_node_html(out: &mut String, node: &Node, depth: usize) {
    if node.hidden {
        return;
    }
    let indent = "  ".repeat(depth);
    let tag = match node.kind {
        NodeKind::Text => "span",
        _ => "div",
    };
    let mut style = format!(
        "position:absolute;left:{}px;top:{}px;width:{}px;height:{}px",
        node.bounds.origin.x,
        node.bounds.origin.y,
        node.bounds.size.x,
        node.bounds.size.y,
    );
    if let Some(fill) = node.fill {
        style.push_str(&format!(";background:{}", color_to_css(fill)));
    }
    if let Some(stroke) = node.stroke {
        style.push_str(&format!(
            ";border:{}px solid {}",
            stroke.width,
            color_to_css(stroke.color)
        ));
    }
    if node.corner_radius > 0.0 {
        style.push_str(&format!(";border-radius:{}px", node.corner_radius));
    }
    if matches!(node.kind, NodeKind::Ellipse) {
        style.push_str(";border-radius:50%");
    }
    if node.rotation.abs() > f32::EPSILON {
        style.push_str(&format!(";transform:rotate({}rad)", node.rotation));
    }
    let body = node.text.clone().unwrap_or_default();
    if node.children.is_empty() && body.is_empty() {
        out.push_str(&format!("{indent}<{tag} style=\"{style}\"></{tag}>\n"));
    } else {
        out.push_str(&format!("{indent}<{tag} style=\"{style}\">"));
        if !body.is_empty() {
            out.push_str(&html_escape(&body));
        }
        if !node.children.is_empty() {
            out.push('\n');
            for c in &node.children {
                emit_node_html(out, c, depth + 1);
            }
            out.push_str(&indent);
        }
        out.push_str(&format!("</{tag}>\n"));
    }
}

/// Vue 3 Single File Component generator. Wraps the page's node
/// tree in a `<template>` block (HTML-like) + an empty `<script
/// setup>` placeholder + a `<style>` block carrying any
/// design-variables-derived custom properties. Mirrors TS
/// `pen-codegen::vue-generator`.
pub struct Vue;

impl Codegen for Vue {
    fn target_label(&self) -> &'static str {
        "vue"
    }
    fn generate(&self, doc: &Document) -> String {
        let mut out = String::new();
        out.push_str("<!-- Generated by OpenPencil — codegen::Vue -->\n");
        out.push_str("<template>\n");
        if let Some(page) = doc.pages.get(doc.active_page_index) {
            for n in &page.children {
                emit_node_html(&mut out, n, 1);
            }
        }
        out.push_str("</template>\n\n");
        out.push_str("<script setup lang=\"ts\">\n// generated\n</script>\n\n");
        out.push_str("<style scoped>\n");
        out.push_str(&CssVariables.generate(doc));
        out.push_str("</style>\n");
        out
    }
}

/// Svelte component generator. Markup + `<style>` block — Svelte
/// allows top-level markup without a wrapping template tag. Same
/// design-variables-as-CSS-vars pattern as Vue.
pub struct Svelte;

impl Codegen for Svelte {
    fn target_label(&self) -> &'static str {
        "svelte"
    }
    fn generate(&self, doc: &Document) -> String {
        let mut out = String::new();
        out.push_str("<!-- Generated by OpenPencil — codegen::Svelte -->\n");
        out.push_str("<script lang=\"ts\">\n// generated\n</script>\n\n");
        if let Some(page) = doc.pages.get(doc.active_page_index) {
            for n in &page.children {
                emit_node_html(&mut out, n, 0);
            }
        }
        out.push_str("\n<style>\n");
        out.push_str(&CssVariables.generate(doc));
        out.push_str("</style>\n");
        out
    }
}

/// React + inline-style JSX generator. Emits one functional
/// component named `Page` returning a fragment of absolute-
/// positioned `<div>`s + text spans. Same per-node mapping as the
/// HTML target; the wrapper is JSX. Mirrors TS
/// `pen-codegen::react-generator` minus Tailwind class generation.
pub struct React;

impl Codegen for React {
    fn target_label(&self) -> &'static str {
        "react"
    }
    fn generate(&self, doc: &Document) -> String {
        let mut out = String::new();
        out.push_str("// Generated by OpenPencil — codegen::React\n");
        out.push_str("import React from 'react';\n\n");
        out.push_str("export default function Page() {\n");
        out.push_str("  return (\n    <>\n");
        if let Some(page) = doc.pages.get(doc.active_page_index) {
            for n in &page.children {
                emit_node_jsx(&mut out, n, 3);
            }
        }
        out.push_str("    </>\n  );\n}\n");
        out
    }
}

fn emit_node_jsx(out: &mut String, node: &Node, depth: usize) {
    if node.hidden {
        return;
    }
    let indent = "  ".repeat(depth);
    let tag = if matches!(node.kind, NodeKind::Text) {
        "span"
    } else {
        "div"
    };
    // JSX style is an object literal — semicolons → commas, camelCase keys.
    let style = format!(
        "position: 'absolute', left: {}, top: {}, width: {}, height: {}{}{}{}{}",
        node.bounds.origin.x,
        node.bounds.origin.y,
        node.bounds.size.x,
        node.bounds.size.y,
        node.fill
            .map(|c| format!(", background: '{}'", color_to_css(c)))
            .unwrap_or_default(),
        node.stroke
            .map(|s| format!(", border: '{}px solid {}'", s.width, color_to_css(s.color)))
            .unwrap_or_default(),
        if node.corner_radius > 0.0 {
            format!(", borderRadius: {}", node.corner_radius)
        } else {
            String::new()
        },
        if matches!(node.kind, NodeKind::Ellipse) {
            ", borderRadius: '50%'".to_string()
        } else {
            String::new()
        },
    );
    let body = node.text.clone().unwrap_or_default();
    if node.children.is_empty() && body.is_empty() {
        out.push_str(&format!("{indent}<{tag} style={{{{{style}}}}} />\n"));
    } else {
        out.push_str(&format!("{indent}<{tag} style={{{{{style}}}}}>"));
        if !body.is_empty() {
            out.push_str(&html_escape(&body));
        }
        if !node.children.is_empty() {
            out.push('\n');
            for c in &node.children {
                emit_node_jsx(out, c, depth + 1);
            }
            out.push_str(&indent);
        }
        out.push_str(&format!("</{tag}>\n"));
    }
}

/// Flutter / Dart generator. Emits a `Stack` whose children are
/// `Positioned`-wrapped `Container`s sized + coloured per node.
/// Text uses `Text(...)` with a `TextStyle`. Mirrors TS
/// `pen-codegen::flutter-generator`.
pub struct Flutter;

impl Codegen for Flutter {
    fn target_label(&self) -> &'static str {
        "flutter"
    }
    fn generate(&self, doc: &Document) -> String {
        let mut out = String::new();
        out.push_str("// Generated by OpenPencil — codegen::Flutter\n");
        out.push_str("import 'package:flutter/material.dart';\n\n");
        out.push_str("Widget buildPage() {\n  return Stack(children: [\n");
        if let Some(page) = doc.pages.get(doc.active_page_index) {
            for n in &page.children {
                emit_node_flutter(&mut out, n, 2);
            }
        }
        out.push_str("  ]);\n}\n");
        out
    }
}

fn emit_node_flutter(out: &mut String, node: &Node, depth: usize) {
    if node.hidden {
        return;
    }
    let indent = "  ".repeat(depth);
    let inner = match node.kind {
        NodeKind::Text => {
            let body = node.text.clone().unwrap_or_default();
            format!("Text({:?})", body)
        }
        _ => {
            let color = node
                .fill
                .map(|c| {
                    let r = (c.r.clamp(0.0, 1.0) * 255.0).round() as u8;
                    let g = (c.g.clamp(0.0, 1.0) * 255.0).round() as u8;
                    let b = (c.b.clamp(0.0, 1.0) * 255.0).round() as u8;
                    let a = (c.a.clamp(0.0, 1.0) * 255.0).round() as u8;
                    format!("Color.fromARGB({},{},{},{})", a, r, g, b)
                })
                .unwrap_or_else(|| "null".into());
            format!(
                "Container(width: {}, height: {}, decoration: BoxDecoration(color: {}))",
                node.bounds.size.x, node.bounds.size.y, color
            )
        }
    };
    out.push_str(&format!(
        "{indent}Positioned(left: {}, top: {}, child: {}),\n",
        node.bounds.origin.x, node.bounds.origin.y, inner
    ));
    for c in &node.children {
        emit_node_flutter(out, c, depth);
    }
}

/// SwiftUI generator. Emits a `ZStack` of `Rectangle`/`Ellipse`/
/// `Text` views with `.frame` + `.offset` modifiers. Mirrors TS
/// `pen-codegen::swiftui-generator`.
pub struct SwiftUi;

impl Codegen for SwiftUi {
    fn target_label(&self) -> &'static str {
        "swiftui"
    }
    fn generate(&self, doc: &Document) -> String {
        let mut out = String::new();
        out.push_str("// Generated by OpenPencil — codegen::SwiftUi\n");
        out.push_str("import SwiftUI\n\nstruct Page: View {\n  var body: some View {\n");
        out.push_str("    ZStack {\n");
        if let Some(page) = doc.pages.get(doc.active_page_index) {
            for n in &page.children {
                emit_node_swiftui(&mut out, n, 3);
            }
        }
        out.push_str("    }\n  }\n}\n");
        out
    }
}

fn emit_node_swiftui(out: &mut String, node: &Node, depth: usize) {
    if node.hidden {
        return;
    }
    let indent = "  ".repeat(depth);
    let view = match node.kind {
        NodeKind::Text => {
            let body = node.text.clone().unwrap_or_default();
            format!("Text({:?})", body)
        }
        NodeKind::Ellipse => "Ellipse()".to_string(),
        _ => "Rectangle()".to_string(),
    };
    let color = node
        .fill
        .map(|c| {
            format!(
                ".foregroundColor(Color(red: {:.3}, green: {:.3}, blue: {:.3}, opacity: {:.3}))",
                c.r, c.g, c.b, c.a
            )
        })
        .unwrap_or_default();
    let cx = node.bounds.origin.x + node.bounds.size.x / 2.0;
    let cy = node.bounds.origin.y + node.bounds.size.y / 2.0;
    out.push_str(&format!(
        "{indent}{view}{color}.frame(width: {}, height: {}).position(x: {}, y: {})\n",
        node.bounds.size.x, node.bounds.size.y, cx, cy
    ));
    for c in &node.children {
        emit_node_swiftui(out, c, depth);
    }
}

/// Android Jetpack Compose generator. Emits a `Box` with
/// `Modifier.offset`/`size` per node + a single fill color.
/// Mirrors TS `pen-codegen::compose-generator`.
pub struct Compose;

impl Codegen for Compose {
    fn target_label(&self) -> &'static str {
        "compose"
    }
    fn generate(&self, doc: &Document) -> String {
        let mut out = String::new();
        out.push_str("// Generated by OpenPencil — codegen::Compose\n");
        out.push_str("import androidx.compose.foundation.*\n");
        out.push_str("import androidx.compose.foundation.layout.*\n");
        out.push_str("import androidx.compose.material3.Text\n");
        out.push_str("import androidx.compose.runtime.Composable\n");
        out.push_str("import androidx.compose.ui.Modifier\n");
        out.push_str("import androidx.compose.ui.graphics.Color\n");
        out.push_str("import androidx.compose.ui.unit.dp\n\n");
        out.push_str("@Composable\nfun Page() {\n  Box(modifier = Modifier.fillMaxSize()) {\n");
        if let Some(page) = doc.pages.get(doc.active_page_index) {
            for n in &page.children {
                emit_node_compose(&mut out, n, 2);
            }
        }
        out.push_str("  }\n}\n");
        out
    }
}

fn emit_node_compose(out: &mut String, node: &Node, depth: usize) {
    if node.hidden {
        return;
    }
    let indent = "  ".repeat(depth);
    match node.kind {
        NodeKind::Text => {
            let body = node.text.clone().unwrap_or_default();
            out.push_str(&format!(
                "{indent}Text(text = {:?}, modifier = Modifier.offset(x = {}.dp, y = {}.dp))\n",
                body, node.bounds.origin.x, node.bounds.origin.y
            ));
        }
        _ => {
            let color = node
                .fill
                .map(|c| {
                    let r = (c.r.clamp(0.0, 1.0) * 255.0).round() as u8;
                    let g = (c.g.clamp(0.0, 1.0) * 255.0).round() as u8;
                    let b = (c.b.clamp(0.0, 1.0) * 255.0).round() as u8;
                    let a = (c.a.clamp(0.0, 1.0) * 255.0).round() as u8;
                    format!(".background(Color({}, {}, {}, {}))", r, g, b, a)
                })
                .unwrap_or_default();
            out.push_str(&format!(
                "{indent}Box(modifier = Modifier.offset(x = {}.dp, y = {}.dp).size(width = {}.dp, height = {}.dp){})\n",
                node.bounds.origin.x, node.bounds.origin.y,
                node.bounds.size.x, node.bounds.size.y,
                color
            ));
        }
    }
    for c in &node.children {
        emit_node_compose(out, c, depth);
    }
}

/// React Native generator. Emits a default-exported functional
/// component with absolute-positioned `<View>`s + `<Text>`s using
/// React Native's `StyleSheet.flatten`-friendly inline style.
/// Mirrors TS `pen-codegen::react-native-generator`.
pub struct ReactNative;

impl Codegen for ReactNative {
    fn target_label(&self) -> &'static str {
        "react-native"
    }
    fn generate(&self, doc: &Document) -> String {
        let mut out = String::new();
        out.push_str("// Generated by OpenPencil — codegen::ReactNative\n");
        out.push_str("import React from 'react';\n");
        out.push_str("import { View, Text } from 'react-native';\n\n");
        out.push_str("export default function Page() {\n  return (\n    <View style={{ flex: 1 }}>\n");
        if let Some(page) = doc.pages.get(doc.active_page_index) {
            for n in &page.children {
                emit_node_rn(&mut out, n, 3);
            }
        }
        out.push_str("    </View>\n  );\n}\n");
        out
    }
}

fn emit_node_rn(out: &mut String, node: &Node, depth: usize) {
    if node.hidden {
        return;
    }
    let indent = "  ".repeat(depth);
    let style = format!(
        "position: 'absolute', left: {}, top: {}, width: {}, height: {}{}{}",
        node.bounds.origin.x,
        node.bounds.origin.y,
        node.bounds.size.x,
        node.bounds.size.y,
        node.fill
            .map(|c| format!(", backgroundColor: '{}'", color_to_css(c)))
            .unwrap_or_default(),
        if node.corner_radius > 0.0 {
            format!(", borderRadius: {}", node.corner_radius)
        } else {
            String::new()
        },
    );
    match node.kind {
        NodeKind::Text => {
            let body = node.text.clone().unwrap_or_default();
            out.push_str(&format!(
                "{indent}<Text style={{{{{style}}}}}>{}</Text>\n",
                html_escape(&body)
            ));
        }
        _ => {
            if node.children.is_empty() {
                out.push_str(&format!("{indent}<View style={{{{{style}}}}} />\n"));
            } else {
                out.push_str(&format!("{indent}<View style={{{{{style}}}}}>\n"));
                for c in &node.children {
                    emit_node_rn(out, c, depth + 1);
                }
                out.push_str(&format!("{indent}</View>\n"));
            }
        }
    }
}

fn color_to_css(c: Color) -> String {
    let r = (c.r.clamp(0.0, 1.0) * 255.0).round() as u8;
    let g = (c.g.clamp(0.0, 1.0) * 255.0).round() as u8;
    let b = (c.b.clamp(0.0, 1.0) * 255.0).round() as u8;
    if c.a >= 0.999 {
        format!("rgb({},{},{})", r, g, b)
    } else {
        format!("rgba({},{},{},{:.3})", r, g, b, c.a)
    }
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn scalar_to_css(s: &VariableScalar) -> String {
    match s {
        VariableScalar::Bool(b) => b.to_string(),
        VariableScalar::Num(n) => n.to_string(),
        VariableScalar::Str(s) => s.clone(),
    }
}

fn css_ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' { c } else { '-' })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::document::{ThemedValue, Variable, VariableKind, VariableTable};
    use std::collections::{BTreeMap, HashMap};

    fn axis(name: &str, value: &str) -> BTreeMap<String, String> {
        let mut m = BTreeMap::new();
        m.insert(name.to_string(), value.to_string());
        m
    }

    #[test]
    fn css_variables_emits_root_scalars() {
        let mut doc = Document::empty();
        doc.var_table = VariableTable {
            variables: vec![
                Variable {
                    name: "primary".into(),
                    kind: VariableKind::Color,
                    value: VariableValue::Scalar(VariableScalar::Str("#0066ff".into())),
                },
                Variable {
                    name: "spacing".into(),
                    kind: VariableKind::Number,
                    value: VariableValue::Scalar(VariableScalar::Num(12.0)),
                },
            ],
            themes: Vec::new(),
            active_theme: BTreeMap::new(),
            fill_refs: HashMap::new(),
            stroke_refs: HashMap::new(),
        };
        let css = CssVariables.generate(&doc);
        assert!(css.contains(":root {"));
        assert!(css.contains("--primary: #0066ff;"));
        assert!(css.contains("--spacing: 12;"));
    }

    #[test]
    fn css_variables_emits_per_theme_block() {
        let mut doc = Document::empty();
        doc.var_table = VariableTable {
            variables: vec![Variable {
                name: "bg".into(),
                kind: VariableKind::Color,
                value: VariableValue::Themed(vec![
                    ThemedValue {
                        value: VariableScalar::Str("#ffffff".into()),
                        theme: Some(axis("mode", "light")),
                    },
                    ThemedValue {
                        value: VariableScalar::Str("#000000".into()),
                        theme: Some(axis("mode", "dark")),
                    },
                ]),
            }],
            themes: Vec::new(),
            active_theme: BTreeMap::new(),
            fill_refs: HashMap::new(),
            stroke_refs: HashMap::new(),
        };
        let css = CssVariables.generate(&doc);
        assert!(css.contains(":root[data-mode=\"light\"]"));
        assert!(css.contains(":root[data-mode=\"dark\"]"));
        assert!(css.contains("--bg: #ffffff;"));
        assert!(css.contains("--bg: #000000;"));
    }

    #[test]
    fn css_variables_sanitises_non_ident_chars() {
        let mut doc = Document::empty();
        doc.var_table.variables.push(Variable {
            name: "primary.color".into(),
            kind: VariableKind::Color,
            value: VariableValue::Scalar(VariableScalar::Str("#f00".into())),
        });
        let css = CssVariables.generate(&doc);
        // Dot replaced with dash so the result is a valid CSS ident.
        assert!(css.contains("--primary-color: #f00;"));
    }

    #[test]
    fn html_emits_doctype_and_body() {
        let doc = Document::empty();
        let html = Html.generate(&doc);
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("<body>"));
        assert!(html.contains("</body>"));
        assert!(html.contains("OpenPencil"));
    }

    #[test]
    fn html_emits_div_per_node_with_position_and_fill() {
        use crate::document::{Node, NodeKind};
        use crate::{Color, Rect};
        let mut doc = Document::empty();
        let page = doc.pages.get_mut(0).unwrap();
        page.children.clear();
        let mut n = Node::leaf("n10", NodeKind::Rect, "r");
        n.bounds = Rect::xywh(20.0, 30.0, 100.0, 50.0);
        n.fill = Some(Color { r: 1.0, g: 0.0, b: 0.0, a: 1.0 });
        page.children.push(n);
        let html = Html.generate(&doc);
        assert!(html.contains("left:20px"));
        assert!(html.contains("top:30px"));
        assert!(html.contains("width:100px"));
        assert!(html.contains("rgb(255,0,0)"));
    }

    #[test]
    fn html_emits_span_for_text_and_escapes_body() {
        use crate::document::{Node, NodeKind};
        use crate::Rect;
        let mut doc = Document::empty();
        let page = doc.pages.get_mut(0).unwrap();
        page.children.clear();
        let mut t = Node::leaf("n10", NodeKind::Text, "t");
        t.bounds = Rect::xywh(0.0, 0.0, 100.0, 24.0);
        t.text = Some("Hello & <world>".into());
        page.children.push(t);
        let html = Html.generate(&doc);
        assert!(html.contains("<span"));
        assert!(html.contains("Hello &amp; &lt;world&gt;"));
    }

    #[test]
    fn vue_emits_template_script_style_blocks() {
        let doc = Document::empty();
        let s = Vue.generate(&doc);
        assert!(s.contains("<template>"));
        assert!(s.contains("</template>"));
        assert!(s.contains("<script setup"));
        assert!(s.contains("<style scoped>"));
    }

    #[test]
    fn svelte_emits_script_then_markup_then_style() {
        let doc = Document::empty();
        let s = Svelte.generate(&doc);
        let script_pos = s.find("<script").unwrap();
        let style_pos = s.find("<style>").unwrap();
        // Script before style — Svelte SFC convention.
        assert!(script_pos < style_pos);
    }

    #[test]
    fn vue_includes_variable_css_in_style_block() {
        use crate::document::{Variable, VariableKind, VariableScalar, VariableTable, VariableValue};
        let mut doc = Document::empty();
        doc.var_table = VariableTable {
            variables: vec![Variable {
                name: "primary".into(),
                kind: VariableKind::Color,
                value: VariableValue::Scalar(VariableScalar::Str("#abc".into())),
            }],
            themes: Vec::new(),
            active_theme: std::collections::BTreeMap::new(),
            fill_refs: HashMap::new(),
            stroke_refs: HashMap::new(),
        };
        let s = Vue.generate(&doc);
        assert!(s.contains("--primary: #abc;"));
    }

    #[test]
    fn react_emits_functional_component_with_jsx_fragment() {
        let doc = Document::empty();
        let s = React.generate(&doc);
        assert!(s.contains("import React from 'react';"));
        assert!(s.contains("export default function Page()"));
        assert!(s.contains("<>"));
        assert!(s.contains("</>"));
    }

    #[test]
    fn flutter_emits_stack_with_positioned_children() {
        use crate::document::{Node, NodeKind};
        use crate::{Color, Rect};
        let mut doc = Document::empty();
        let page = doc.pages.get_mut(0).unwrap();
        page.children.clear();
        let mut n = Node::leaf("n10", NodeKind::Rect, "r");
        n.bounds = Rect::xywh(5.0, 10.0, 100.0, 50.0);
        n.fill = Some(Color { r: 1.0, g: 0.0, b: 0.0, a: 1.0 });
        page.children.push(n);
        let s = Flutter.generate(&doc);
        assert!(s.contains("import 'package:flutter/material.dart';"));
        assert!(s.contains("Stack(children:"));
        assert!(s.contains("Positioned(left: 5, top: 10"));
        assert!(s.contains("Container(width: 100, height: 50"));
        assert!(s.contains("Color.fromARGB(255,255,0,0)"));
    }

    #[test]
    fn swiftui_emits_zstack_with_positioned_views() {
        use crate::document::{Node, NodeKind};
        use crate::Rect;
        let mut doc = Document::empty();
        let page = doc.pages.get_mut(0).unwrap();
        page.children.clear();
        let mut n = Node::leaf("n10", NodeKind::Rect, "r");
        n.bounds = Rect::xywh(0.0, 0.0, 100.0, 50.0);
        page.children.push(n);
        let s = SwiftUi.generate(&doc);
        assert!(s.contains("import SwiftUI"));
        assert!(s.contains("ZStack {"));
        assert!(s.contains("Rectangle()"));
        assert!(s.contains(".frame(width: 100, height: 50)"));
    }

    #[test]
    fn swiftui_emits_ellipse_for_ellipse_kind() {
        use crate::document::{Node, NodeKind};
        use crate::Rect;
        let mut doc = Document::empty();
        let page = doc.pages.get_mut(0).unwrap();
        page.children.clear();
        let mut n = Node::leaf("n10", NodeKind::Ellipse, "e");
        n.bounds = Rect::xywh(0.0, 0.0, 20.0, 20.0);
        page.children.push(n);
        let s = SwiftUi.generate(&doc);
        assert!(s.contains("Ellipse()"));
    }

    #[test]
    fn compose_emits_composable_box_with_offset_size() {
        use crate::document::{Node, NodeKind};
        use crate::{Color, Rect};
        let mut doc = Document::empty();
        let page = doc.pages.get_mut(0).unwrap();
        page.children.clear();
        let mut n = Node::leaf("n10", NodeKind::Rect, "r");
        n.bounds = Rect::xywh(5.0, 10.0, 100.0, 50.0);
        n.fill = Some(Color { r: 1.0, g: 0.0, b: 0.0, a: 1.0 });
        page.children.push(n);
        let s = Compose.generate(&doc);
        assert!(s.contains("@Composable"));
        assert!(s.contains("Modifier.offset(x = 5.dp, y = 10.dp)"));
        assert!(s.contains("size(width = 100.dp, height = 50.dp)"));
        assert!(s.contains("Color(255, 0, 0, 255)"));
    }

    #[test]
    fn react_native_emits_view_tree_with_absolute_positions() {
        use crate::document::{Node, NodeKind};
        use crate::Rect;
        let mut doc = Document::empty();
        let page = doc.pages.get_mut(0).unwrap();
        page.children.clear();
        let mut n = Node::leaf("n10", NodeKind::Rect, "r");
        n.bounds = Rect::xywh(0.0, 0.0, 80.0, 40.0);
        page.children.push(n);
        let s = ReactNative.generate(&doc);
        assert!(s.contains("import { View, Text } from 'react-native';"));
        assert!(s.contains("export default function Page()"));
        assert!(s.contains("<View style={{"));
        assert!(s.contains("position: 'absolute'"));
        assert!(s.contains("width: 80, height: 40"));
    }

    #[test]
    fn html_skips_hidden_nodes() {
        use crate::document::{Node, NodeKind};
        let mut doc = Document::empty();
        let page = doc.pages.get_mut(0).unwrap();
        page.children.clear();
        let mut n = Node::leaf("n10", NodeKind::Rect, "hidden");
        n.hidden = true;
        page.children.push(n);
        let html = Html.generate(&doc);
        assert!(!html.contains("hidden"));
    }

    #[test]
    fn css_variables_empty_doc_emits_header_only() {
        let doc = Document::empty();
        let css = CssVariables.generate(&doc);
        assert!(css.contains("Generated by OpenPencil"));
        assert!(!css.contains(":root"));
    }
}
