//! Code generation — Rust ports of `packages/pen-codegen/src/`.
//! v1 ships the simplest of the 9 TS generators: `css-variables`,
//! which emits the design's `Document.var_table` as CSS custom
//! properties. Future generators (React + Tailwind, HTML, Vue,
//! Svelte, Flutter, SwiftUI, Compose, React Native) live behind
//! the same `Codegen` trait so a single dispatcher (eventually a
//! `op codegen <target>` CLI) can fan out by target enum.

use crate::document::{Document, Node, NodeKind, VariableScalar, VariableValue};
use crate::Color;

/// One generator. Implementations are pure (read `Document`, return
/// `String`); the CLI / panel layer owns file-write side effects.
pub trait Codegen {
    fn target_label(&self) -> &'static str;
    fn generate(&self, doc: &Document) -> String;
}

/// CSS custom properties generator. Walks `doc.var_table` and emits
/// `:root { --name: value; }`. Color variables stay as their hex
/// string; number/bool/string variables stringify their scalar.
/// Themed values emit ONE entry per theme combination using a
/// `:root[data-axis="value"]` selector so the same CSS reflows
/// across theme switches with no JS.
pub struct CssVariables;

impl Codegen for CssVariables {
    fn target_label(&self) -> &'static str {
        "css-variables"
    }
    fn generate(&self, doc: &Document) -> String {
        let mut out = String::new();
        out.push_str("/* Generated by OpenPencil — codegen::CssVariables */\n");
        // Pass 1: scalar (theme-agnostic) variables go under :root.
        let mut root_scalars: Vec<(String, String)> = Vec::new();
        for v in &doc.var_table.variables {
            if let VariableValue::Scalar(s) = &v.value {
                root_scalars.push((v.name.clone(), scalar_to_css(s)));
            }
        }
        if !root_scalars.is_empty() {
            out.push_str(":root {\n");
            for (name, value) in &root_scalars {
                out.push_str(&format!("  --{}: {};\n", css_ident(name), value));
            }
            out.push_str("}\n");
        }
        // Pass 2: themed variables → one block per (axis, value) combo.
        // Group entries by their theme map signature so a "mode=dark"
        // entry from variable A and another from B share one block.
        use std::collections::BTreeMap;
        let mut themed: BTreeMap<Vec<(String, String)>, Vec<(String, String)>> = BTreeMap::new();
        for v in &doc.var_table.variables {
            if let VariableValue::Themed(entries) = &v.value {
                for e in entries {
                    let key: Vec<(String, String)> = e
                        .theme
                        .as_ref()
                        .map(|m| m.iter().map(|(k, v)| (k.clone(), v.clone())).collect())
                        .unwrap_or_default();
                    themed
                        .entry(key)
                        .or_default()
                        .push((v.name.clone(), scalar_to_css(&e.value)));
                }
            }
        }
        for (axes, decls) in &themed {
            if axes.is_empty() {
                out.push_str(":root {\n");
            } else {
                let sel = axes
                    .iter()
                    .map(|(k, v)| format!("[data-{}=\"{}\"]", k, v))
                    .collect::<Vec<_>>()
                    .join("");
                out.push_str(&format!(":root{} {{\n", sel));
            }
            for (name, value) in decls {
                out.push_str(&format!("  --{}: {};\n", css_ident(name), value));
            }
            out.push_str("}\n");
        }
        out
    }
}

/// HTML + inline-CSS generator. Walks the active page's node tree
/// and emits `<div>` per Rect/Frame/Group with absolute positioning
/// and inline style; ellipses get `border-radius: 50%`; text nodes
/// emit `<span>`. Bare minimum useful — refining to semantic tags
/// + flex containers is a follow-up.
pub struct Html;

impl Codegen for Html {
    fn target_label(&self) -> &'static str {
        "html"
    }
    fn generate(&self, doc: &Document) -> String {
        let mut out = String::new();
        out.push_str("<!-- Generated by OpenPencil — codegen::Html -->\n");
        out.push_str("<!DOCTYPE html>\n<html><head><meta charset=\"utf-8\"></head>\n<body>\n");
        if let Some(page) = doc.pages.get(doc.active_page_index) {
            for node in &page.children {
                emit_node_html(&mut out, node, 1);
            }
        }
        out.push_str("</body></html>\n");
        out
    }
}

fn emit_node_html(out: &mut String, node: &Node, depth: usize) {
    if node.hidden {
        return;
    }
    let indent = "  ".repeat(depth);
    let tag = match node.kind {
        NodeKind::Text => "span",
        _ => "div",
    };
    let mut style = format!(
        "position:absolute;left:{}px;top:{}px;width:{}px;height:{}px",
        node.bounds.origin.x,
        node.bounds.origin.y,
        node.bounds.size.x,
        node.bounds.size.y,
    );
    if let Some(fill) = node.fill {
        style.push_str(&format!(";background:{}", color_to_css(fill)));
    }
    if let Some(stroke) = node.stroke {
        style.push_str(&format!(
            ";border:{}px solid {}",
            stroke.width,
            color_to_css(stroke.color)
        ));
    }
    if node.corner_radius > 0.0 {
        style.push_str(&format!(";border-radius:{}px", node.corner_radius));
    }
    if matches!(node.kind, NodeKind::Ellipse) {
        style.push_str(";border-radius:50%");
    }
    if node.rotation.abs() > f32::EPSILON {
        style.push_str(&format!(";transform:rotate({}rad)", node.rotation));
    }
    let body = node.text.clone().unwrap_or_default();
    if node.children.is_empty() && body.is_empty() {
        out.push_str(&format!("{indent}<{tag} style=\"{style}\"></{tag}>\n"));
    } else {
        out.push_str(&format!("{indent}<{tag} style=\"{style}\">"));
        if !body.is_empty() {
            out.push_str(&html_escape(&body));
        }
        if !node.children.is_empty() {
            out.push('\n');
            for c in &node.children {
                emit_node_html(out, c, depth + 1);
            }
            out.push_str(&indent);
        }
        out.push_str(&format!("</{tag}>\n"));
    }
}

fn color_to_css(c: Color) -> String {
    let r = (c.r.clamp(0.0, 1.0) * 255.0).round() as u8;
    let g = (c.g.clamp(0.0, 1.0) * 255.0).round() as u8;
    let b = (c.b.clamp(0.0, 1.0) * 255.0).round() as u8;
    if c.a >= 0.999 {
        format!("rgb({},{},{})", r, g, b)
    } else {
        format!("rgba({},{},{},{:.3})", r, g, b, c.a)
    }
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn scalar_to_css(s: &VariableScalar) -> String {
    match s {
        VariableScalar::Bool(b) => b.to_string(),
        VariableScalar::Num(n) => n.to_string(),
        VariableScalar::Str(s) => s.clone(),
    }
}

fn css_ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' { c } else { '-' })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::document::{ThemedValue, Variable, VariableKind, VariableTable};
    use std::collections::BTreeMap;

    fn axis(name: &str, value: &str) -> BTreeMap<String, String> {
        let mut m = BTreeMap::new();
        m.insert(name.to_string(), value.to_string());
        m
    }

    #[test]
    fn css_variables_emits_root_scalars() {
        let mut doc = Document::empty();
        doc.var_table = VariableTable {
            variables: vec![
                Variable {
                    name: "primary".into(),
                    kind: VariableKind::Color,
                    value: VariableValue::Scalar(VariableScalar::Str("#0066ff".into())),
                },
                Variable {
                    name: "spacing".into(),
                    kind: VariableKind::Number,
                    value: VariableValue::Scalar(VariableScalar::Num(12.0)),
                },
            ],
            themes: Vec::new(),
            active_theme: BTreeMap::new(),
        };
        let css = CssVariables.generate(&doc);
        assert!(css.contains(":root {"));
        assert!(css.contains("--primary: #0066ff;"));
        assert!(css.contains("--spacing: 12;"));
    }

    #[test]
    fn css_variables_emits_per_theme_block() {
        let mut doc = Document::empty();
        doc.var_table = VariableTable {
            variables: vec![Variable {
                name: "bg".into(),
                kind: VariableKind::Color,
                value: VariableValue::Themed(vec![
                    ThemedValue {
                        value: VariableScalar::Str("#ffffff".into()),
                        theme: Some(axis("mode", "light")),
                    },
                    ThemedValue {
                        value: VariableScalar::Str("#000000".into()),
                        theme: Some(axis("mode", "dark")),
                    },
                ]),
            }],
            themes: Vec::new(),
            active_theme: BTreeMap::new(),
        };
        let css = CssVariables.generate(&doc);
        assert!(css.contains(":root[data-mode=\"light\"]"));
        assert!(css.contains(":root[data-mode=\"dark\"]"));
        assert!(css.contains("--bg: #ffffff;"));
        assert!(css.contains("--bg: #000000;"));
    }

    #[test]
    fn css_variables_sanitises_non_ident_chars() {
        let mut doc = Document::empty();
        doc.var_table.variables.push(Variable {
            name: "primary.color".into(),
            kind: VariableKind::Color,
            value: VariableValue::Scalar(VariableScalar::Str("#f00".into())),
        });
        let css = CssVariables.generate(&doc);
        // Dot replaced with dash so the result is a valid CSS ident.
        assert!(css.contains("--primary-color: #f00;"));
    }

    #[test]
    fn html_emits_doctype_and_body() {
        let doc = Document::empty();
        let html = Html.generate(&doc);
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("<body>"));
        assert!(html.contains("</body>"));
        assert!(html.contains("OpenPencil"));
    }

    #[test]
    fn html_emits_div_per_node_with_position_and_fill() {
        use crate::document::{Node, NodeKind};
        use crate::{Color, Rect};
        let mut doc = Document::empty();
        let page = doc.pages.get_mut(0).unwrap();
        page.children.clear();
        let mut n = Node::leaf(10, NodeKind::Rect, "r");
        n.bounds = Rect::xywh(20.0, 30.0, 100.0, 50.0);
        n.fill = Some(Color { r: 1.0, g: 0.0, b: 0.0, a: 1.0 });
        page.children.push(n);
        let html = Html.generate(&doc);
        assert!(html.contains("left:20px"));
        assert!(html.contains("top:30px"));
        assert!(html.contains("width:100px"));
        assert!(html.contains("rgb(255,0,0)"));
    }

    #[test]
    fn html_emits_span_for_text_and_escapes_body() {
        use crate::document::{Node, NodeKind};
        use crate::Rect;
        let mut doc = Document::empty();
        let page = doc.pages.get_mut(0).unwrap();
        page.children.clear();
        let mut t = Node::leaf(10, NodeKind::Text, "t");
        t.bounds = Rect::xywh(0.0, 0.0, 100.0, 24.0);
        t.text = Some("Hello & <world>".into());
        page.children.push(t);
        let html = Html.generate(&doc);
        assert!(html.contains("<span"));
        assert!(html.contains("Hello &amp; &lt;world&gt;"));
    }

    #[test]
    fn html_skips_hidden_nodes() {
        use crate::document::{Node, NodeKind};
        let mut doc = Document::empty();
        let page = doc.pages.get_mut(0).unwrap();
        page.children.clear();
        let mut n = Node::leaf(10, NodeKind::Rect, "hidden");
        n.hidden = true;
        page.children.push(n);
        let html = Html.generate(&doc);
        assert!(!html.contains("hidden"));
    }

    #[test]
    fn css_variables_empty_doc_emits_header_only() {
        let doc = Document::empty();
        let css = CssVariables.generate(&doc);
        assert!(css.contains("Generated by OpenPencil"));
        assert!(!css.contains(":root"));
    }
}
