//! Code generation — Rust ports of `packages/pen-codegen/src/`.
//! v1 ships the simplest of the 9 TS generators: `css-variables`,
//! which emits the design's `Document.var_table` as CSS custom
//! properties. Future generators (React + Tailwind, HTML, Vue,
//! Svelte, Flutter, SwiftUI, Compose, React Native) live behind
//! the same `Codegen` trait so a single dispatcher (eventually a
//! `op codegen <target>` CLI) can fan out by target enum.

use crate::document::{Document, VariableScalar, VariableValue};

/// One generator. Implementations are pure (read `Document`, return
/// `String`); the CLI / panel layer owns file-write side effects.
pub trait Codegen {
    fn target_label(&self) -> &'static str;
    fn generate(&self, doc: &Document) -> String;
}

/// CSS custom properties generator. Walks `doc.var_table` and emits
/// `:root { --name: value; }`. Color variables stay as their hex
/// string; number/bool/string variables stringify their scalar.
/// Themed values emit ONE entry per theme combination using a
/// `:root[data-axis="value"]` selector so the same CSS reflows
/// across theme switches with no JS.
pub struct CssVariables;

impl Codegen for CssVariables {
    fn target_label(&self) -> &'static str {
        "css-variables"
    }
    fn generate(&self, doc: &Document) -> String {
        let mut out = String::new();
        out.push_str("/* Generated by OpenPencil — codegen::CssVariables */\n");
        // Pass 1: scalar (theme-agnostic) variables go under :root.
        let mut root_scalars: Vec<(String, String)> = Vec::new();
        for v in &doc.var_table.variables {
            if let VariableValue::Scalar(s) = &v.value {
                root_scalars.push((v.name.clone(), scalar_to_css(s)));
            }
        }
        if !root_scalars.is_empty() {
            out.push_str(":root {\n");
            for (name, value) in &root_scalars {
                out.push_str(&format!("  --{}: {};\n", css_ident(name), value));
            }
            out.push_str("}\n");
        }
        // Pass 2: themed variables → one block per (axis, value) combo.
        // Group entries by their theme map signature so a "mode=dark"
        // entry from variable A and another from B share one block.
        use std::collections::BTreeMap;
        let mut themed: BTreeMap<Vec<(String, String)>, Vec<(String, String)>> = BTreeMap::new();
        for v in &doc.var_table.variables {
            if let VariableValue::Themed(entries) = &v.value {
                for e in entries {
                    let key: Vec<(String, String)> = e
                        .theme
                        .as_ref()
                        .map(|m| m.iter().map(|(k, v)| (k.clone(), v.clone())).collect())
                        .unwrap_or_default();
                    themed
                        .entry(key)
                        .or_default()
                        .push((v.name.clone(), scalar_to_css(&e.value)));
                }
            }
        }
        for (axes, decls) in &themed {
            if axes.is_empty() {
                out.push_str(":root {\n");
            } else {
                let sel = axes
                    .iter()
                    .map(|(k, v)| format!("[data-{}=\"{}\"]", k, v))
                    .collect::<Vec<_>>()
                    .join("");
                out.push_str(&format!(":root{} {{\n", sel));
            }
            for (name, value) in decls {
                out.push_str(&format!("  --{}: {};\n", css_ident(name), value));
            }
            out.push_str("}\n");
        }
        out
    }
}

fn scalar_to_css(s: &VariableScalar) -> String {
    match s {
        VariableScalar::Bool(b) => b.to_string(),
        VariableScalar::Num(n) => n.to_string(),
        VariableScalar::Str(s) => s.clone(),
    }
}

fn css_ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '-' { c } else { '-' })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::document::{ThemedValue, Variable, VariableKind, VariableTable};
    use std::collections::BTreeMap;

    fn axis(name: &str, value: &str) -> BTreeMap<String, String> {
        let mut m = BTreeMap::new();
        m.insert(name.to_string(), value.to_string());
        m
    }

    #[test]
    fn css_variables_emits_root_scalars() {
        let mut doc = Document::empty();
        doc.var_table = VariableTable {
            variables: vec![
                Variable {
                    name: "primary".into(),
                    kind: VariableKind::Color,
                    value: VariableValue::Scalar(VariableScalar::Str("#0066ff".into())),
                },
                Variable {
                    name: "spacing".into(),
                    kind: VariableKind::Number,
                    value: VariableValue::Scalar(VariableScalar::Num(12.0)),
                },
            ],
            themes: Vec::new(),
            active_theme: BTreeMap::new(),
        };
        let css = CssVariables.generate(&doc);
        assert!(css.contains(":root {"));
        assert!(css.contains("--primary: #0066ff;"));
        assert!(css.contains("--spacing: 12;"));
    }

    #[test]
    fn css_variables_emits_per_theme_block() {
        let mut doc = Document::empty();
        doc.var_table = VariableTable {
            variables: vec![Variable {
                name: "bg".into(),
                kind: VariableKind::Color,
                value: VariableValue::Themed(vec![
                    ThemedValue {
                        value: VariableScalar::Str("#ffffff".into()),
                        theme: Some(axis("mode", "light")),
                    },
                    ThemedValue {
                        value: VariableScalar::Str("#000000".into()),
                        theme: Some(axis("mode", "dark")),
                    },
                ]),
            }],
            themes: Vec::new(),
            active_theme: BTreeMap::new(),
        };
        let css = CssVariables.generate(&doc);
        assert!(css.contains(":root[data-mode=\"light\"]"));
        assert!(css.contains(":root[data-mode=\"dark\"]"));
        assert!(css.contains("--bg: #ffffff;"));
        assert!(css.contains("--bg: #000000;"));
    }

    #[test]
    fn css_variables_sanitises_non_ident_chars() {
        let mut doc = Document::empty();
        doc.var_table.variables.push(Variable {
            name: "primary.color".into(),
            kind: VariableKind::Color,
            value: VariableValue::Scalar(VariableScalar::Str("#f00".into())),
        });
        let css = CssVariables.generate(&doc);
        // Dot replaced with dash so the result is a valid CSS ident.
        assert!(css.contains("--primary-color: #f00;"));
    }

    #[test]
    fn css_variables_empty_doc_emits_header_only() {
        let doc = Document::empty();
        let css = CssVariables.generate(&doc);
        assert!(css.contains("Generated by OpenPencil"));
        assert!(!css.contains(":root"));
    }
}
